<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <NoWarn>$(NoWarn);CA1000;CA1716</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <AhrFoundationVersion Condition="'$(AhrFoundationVersion)' == ''">0.1.1</AhrFoundationVersion>
    <Version>$(AhrFoundationVersion)</Version>
    <VersionPrefix Condition="$([System.String]::Copy('$(AhrFoundationVersion)').Contains('-')) == 'false'">$(AhrFoundationVersion)</VersionPrefix>
    <Authors>AHR Consulting</Authors>
    <Company>AHR Consulting</Company>
    <Product>AHR Foundation</Product>
    <Copyright>Copyright © 2026 AHR Consulting</Copyright>
    <RepositoryUrl>https://github.com/AHRConsulting/Ahr.Foundation</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>
</Project>
