<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Ahr.Foundation.Benchmarks</RootNamespace>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <NoWarn>$(NoWarn);IDE0005;CA1822</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Ahr.Foundation\Ahr.Foundation.csproj" />
  </ItemGroup>
</Project>
